---
Name: coreenvironmentchecks
---
SilverStripe\EnvironmentCheck\EnvironmentCheckSuite:
  registered_checks:
    db:
      definition: 'SilverStripe\EnvironmentCheck\Checks\DatabaseCheck()'
      title: 'Is the database accessible?'
  registered_suites:
    health:
      - db
